name: Auto-Create PR on Push

on:
  push:
    branches:
      - 'feature/**'  # Пуш в любую ветку, начинающуюся с feature/

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto-PR: Changes from ${{ github.ref }}"
          body: "Automated PR created from push to ${{ github.ref }}"
          base: main   # Ветка, в которую мерджим
          draft: false
          labels: "automated-pr"
